version: '3'

networks:
  laravel:

services:
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - .:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysql
      networks:
       - laravel

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './mysql:/var/lib/mysql'
        networks:
            - laravel

    php:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: php
      volumes:
        - .:/var/www/html
      ports:
      - "9000:9000"
      networks:
        - laravel

    composer:
      image: composer:latest
      container_name: composer
      volumes:
        - .:/var/www/html
      working_dir: /var/www/html
      networks:
        - laravel
